### ISSUE TITLE
Build farm failing for swri_cli_tools

### ISSUE THREAD

**Issue by rjb0026** [swri-robotics/marti_common#686]
ROS build farm jobs for melodic are consistently failing for the swri_cli_tools package during the "build binarydeb" stage. The following error during building appears to be the source of the build failure:

03:03:55 Traceback (most recent call last):
03:03:56   File "/opt/ros/melodic/share/catkin/cmake/interrogate_setup_dot_py.py", line 255, in <module>
03:03:56     main()
03:03:56   File "/opt/ros/melodic/share/catkin/cmake/interrogate_setup_dot_py.py", line 248, in main
03:03:56     runpy.run_path(args.setupfile_path)
03:03:56   File "/usr/lib/python2.7/runpy.py", line 252, in run_path
03:03:56     return _run_module_code(code, init_globals, run_name, path_name)
03:03:56   File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
03:03:56     mod_name, mod_fname, mod_loader, pkg_name)
03:03:56   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
03:03:56     exec code in run_globals
03:03:56   File "/tmp/binarydeb/ros-melodic-swri-cli-tools-2.15.2/setup.py", line 1, in <module>
03:03:56     from setuptools import setup
03:03:56 ImportError: No module named setuptools

The `distutils.core` package should be used to import the `setup` function instead.

**Comment by rjb0026** [comment]
Added fallback to `distutils.core.setup` in #687
